# Generated by Django 3.0.6 on 2020-05-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URL_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shortener',
            new_name='UrlForm',
        ),
    ]
