# Generated by Django 3.0.6 on 2020-05-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desp',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
