# Generated by Django 3.0.6 on 2020-05-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_book_desp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desp',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
