# Generated by Django 3.0.6 on 2020-05-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0004_auto_20200518_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desp',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
