# Generated by Django 3.0.6 on 2020-05-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0005_auto_20200518_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
