# Generated by Django 3.0.6 on 2020-05-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0006_checkout_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'available'), ('u', 'unavailable')], default='a', help_text='book availability', max_length=1),
        ),
    ]
