# Generated by Django 3.0.6 on 2020-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0007_checkout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='checked_out',
        ),
    ]
