# Generated by Django 3.0.6 on 2020-05-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0009_auto_20200522_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='book',
            new_name='book_id',
        ),
    ]
