# Generated by Django 3.0.6 on 2020-05-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0010_auto_20200526_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='book_id',
            new_name='book',
        ),
    ]
