# Generated by Django 3.0.6 on 2020-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0011_auto_20200526_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'available'), ('u', 'unavailable')], default='a', help_text='book availability', max_length=1),
        ),
    ]
