# Generated by Django 3.0.5 on 2020-04-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='task',
        ),
    ]
