# Generated by Django 3.0.5 on 2020-04-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20200427_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desp',
            field=models.TextField(),
        ),
    ]
