# Generated by Django 3.0.5 on 2020-05-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20200429_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='desp',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
